# AFK SERVERS DEFINED IN THE BUNGEE PLUGINS CONFIG.YML GO HERE!
limbos:
  - "first"

# In SECONDS!
# How long should we wait before we define the player as AFK ?
afk-time: 20

afk-message: "&cYou will be AFK in &e&l10 seconds!"